cloudformation.yaml
=> Issue 3.ron.0

cloudformation.yaml
=> #6 added sqs producer policy

cloudformation.yaml
=> Issue 8.chia.1

.project, README.md, cloudformation.yaml, examples/demo.py, examples/requirements.txt
=> Issue 12.dockter.1

CHANGELOG.md, README.md, cloudformation.yaml, cloudformationV2.yaml
Issue number: #16 #17 #21 #22
???
???
=> Issue 16.ron.0

CONTRIBUTING.md, README.md, docs/details.md, examples/cli_demo.py, examples/webapp_demo.py
=> #19 Migrate from master to main

CHANGELOG.md, cloudformation.yaml
=> #29 added images to outputs

README.md, docs/postman.md
=> Issue 26.dockter.1

.pylintrc
=> #25 Add pylint

CHANGELOG.md, cloudformation.yaml
=> #30 updated images and senzing versions

README.md
=> #35 updated readme

CHANGELOG.md, cloudformation.yaml
=> #39 added engine config support for single database

CHANGELOG.md, README.md
=> #38 updated readme to point to SwaggerUI

README.md, cloudformation.yaml
Issue number: #42
add in keystore generator
=> Issue 42.chia.0

CHANGELOG.md, cloudformation.yaml
=> #45 update to Senzing 3.3.1

CHANGELOG.md, cloudformation.yaml
=> #47 updated senzing version

CHANGELOG.md, cloudformation.yaml
=> #49 updated senzing version

.gitignore, README.md
=> #54 Update links

CHANGELOG.md, cloudformation.yaml
=> #57 updated docker images, change log and versioning release

CHANGELOG.md, cloudformation.yaml
=> #59 updated senzing and docker image versions

CHANGELOG.md, cloudformation.yaml
=> #61 update docker images and senzing version

README.md
=> #63 Prepare for deprecation
